CREATE DATABASE IF NOT EXISTS todo_app;
USE todo_app;
DROP TABLE IF EXISTS Todo;
CREATE TABLE Todo (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  description VARCHAR(255) NOT NULL,
  completedAt DATETIME,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);